services:
  api:
    build: .
    container_name: fund_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    entrypoint: ["sh", "-c", "sed -i 's/\\r//' /app/docker-entrypoint.sh && sh /app/docker-entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fund_network

  db:
    image: postgres:16-alpine
    container_name: fund_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fund_network

volumes:
  pgdata:

networks:
  fund_network:
    driver: bridge